name: server_status
description: System monitoring of home server 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.2
  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  async: ^2.12.0
  flutter_secure_storage: ^9.2.4
  flutter_form_builder: ^10.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true